name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install

      - name: Create Release Pull Request
        id: changeset_action
        uses: changesets/action@v1
        with:
          publish: pnpm run release_packages
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CHANGESET_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: get files
        run: |
          pwd
          ls -a

      - name: Get branch name before
        run: echo "${{ github.head_ref }}"

      - name: show pull request number
        run: echo "the pr number is ${{ steps.changeset_action.outputs.pullRequestNumber }}"

      - name: Checkout PR
        if: ${{ !steps.changeset_action.outputs.published }}
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ steps.changeset_action.outputs.pullRequestNumber }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Running on the branch.
        run: |
          echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"
