name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_CHANGESET_TOKEN }}
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: show location
        run: pwd

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER --global

      - name: install dependencies
        run: pnpm install

      - name: Create Release Pull Request
        id: changeset_action
        uses: changesets/action@v1
        with:
          publish: pnpm run release_packages
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CHANGESET_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Show outputs
        run: |
          echo "is publish ${{ steps.changeset_action.outputs.published }}"
          echo "pr number ${{ steps.changeset_action.outputs.pullRequestNumber }}"
          echo "pr base ref branch ${GITHUB_BASE_REF}"
          echo "pr branch ${GITHUB_REF}"

      - name: Verify publish
        if: ${{ steps.changeset_action.outputs.published == 'true' }}
        run: echo "pr published packages"

      - name: Verify not publish
        if: ${{ steps.changeset_action.outputs.published != 'true' }}
        run: echo "pr not published packages"

      - name: Try action
        if: ${{ steps.changeset_action.outputs.published != 'true' }}
        uses: ./actions/compiled_try_action
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CHANGESET_TOKEN }}
