name: Run Action

on:
  push:
    branches:
      - bnxcbcxn

jobs:
  run-custom-action:
    name: Run Custom Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run custom action
        uses: ./actions/compiled_action
