name: Verify Changesets

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v21

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Check if changesets exists
        if: contains(steps.changed-files.outputs.all_changed_files, '^changeset/.+')
        run: |
          echo "a changeset exists"
      - name: Print array
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Loop over file list
        env:
          CHANGESET_EXISTS: ${{ false }}
        run: |
          for fileIn in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $fileIn
            if [[ $fileIn == .changeset/* ]] && [[ $fileIn == *.md ]] ; then
              echo "$fileIn is a changeset"
            else
              echo "$fileIn is not a changeset"
            fi
          done
